# Generated by Django 2.0 on 2018-01-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blog_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='blogs.Post'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_name',
            field=models.URLField(),
        ),
    ]
