# Generated by Django 2.0 on 2018-01-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_remove_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
    ]
