# Generated by Django 2.0 on 2018-01-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blogs.Blog'),
            preserve_default=False,
        ),
    ]
