# Generated by Django 2.0 on 2018-01-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20180107_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
