# Generated by Django 2.0 on 2018-01-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='author',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
