# Generated by Django 2.0 on 2018-01-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('blogs', '0017_auto_20180108_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
