# Generated by Django 2.0 on 2018-01-15 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_auto_20180110_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 15, 0, 0, 19, 246109)),
        ),
    ]
